services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  consumer-ativacao:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
    command: sh -c "npx prisma migrate deploy && node dist/infrastructure/messaging/consume-veiculo-em-ativacao.js"

  consumer-desativacao:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
    command: sh -c "npx prisma migrate deploy && node dist/infrastructure/messaging/consume-veiculo-em-desativacao.js"

  frontend:
    build: ./frontend
    ports:
      - '4200:80'
    depends_on:
      - app 